In [1]:
import pandas as pd
import time
import os
import csv

from selenium import webdriver
from selenium.webdriver.common.by import By
# from seleniumFunction import *
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# ==================== GLOBAL VARIABLES
# Set Chrome options:
chrome_options = Options()
# chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox') 
chrome_options.add_argument("--incognito")
chrome_options.add_argument("--start-maximized")
chrome_options.add_argument("--disable-application-cache")
chrome_options.add_argument("--disable-cache")
chrome_options.add_argument("--disk-cache-size=0")

In [121]:
%%capture
df = pd.read_csv('vietnam_accommodation.csv')
df.shape

In [123]:
df.head(1).T

                                                                              0
hotel_id                                                                    163
hotel_name                                                  Ramana Saigon Hotel
addressline1                                 323 Le Van Sy Street, District 3
city                                                           Ho Chi Minh City
state                                                                       NaN
longitude                                                            106.678101
latitude                                                              10.787597
url                           https://www.agoda.com/partners/partnersearch.a...
numberrooms                                                               296.0
yearopened                                                               1996.0
yearrenovated                                                            2015.0
number_of_reviews                                                          1713
rating_average                                                              8.1
star_rating                                                                 4.0
boat/cruise                                                                   0
capsule hotel                                                                 0
chalet                                                                        0
country house                                                                 0
entire apartment                                                              0
entire bungalow                                                               0
entire house                                                                  0
entire villa                                                                  0
farm stay                                                                     0
guesthouse/bed and breakfast                                                  0
holiday park/caravan park                                                     0
homestay                                                                      0
hostel                                                                        0
hotel                                                                         1
inn                                                                           0
lodge                                                                         0
love hotel                                                                    0
motel                                                                         0
resort                                                                        0
resort villa                                                                  0
serviced apartment                                                            0
tent                                                                          0

In [99]:
df.head(1).T

                                                                       0
hotel_id                                                             163
chain_id                                                               0
chain_name                                                      No chain
brand_id                                                               0
brand_name                                                           NaN
hotel_name                                           Ramana Saigon Hotel
hotel_formerly_name                                          Amara Hotel
hotel_translated_name                                Ramana Saigon Hotel
addressline1                          323 Le Van Sy Street, District 3
addressline2                                                         NaN
zipcode
city                                                    Ho Chi Minh City
state                                                                NaN
country                                                          Vietnam
countryisocode                                                        VN
star_rating                                                          4.0
longitude                                                     106.678101
latitude                                                       10.787597
url                    https://www.agoda.com/partners/partnersearch.a...
checkin                                                         02:00 PM
checkout                                                        12:00 PM
numberrooms                                                        296.0
numberfloors                                                         9.0
yearopened                                                        1996.0
yearrenovated                                                     2015.0
photo1                 http://pix5.agoda.net/hotelimages/163/-1/63ac3...
photo2                 http://pix2.agoda.net/hotelimages/163/-1/31514...
photo3                 http://pix5.agoda.net/hotelimages/163/163/163_...
photo4                 http://pix2.agoda.net/hotelimages/163/163/163_...
photo5                 http://pix1.agoda.net/hotelimages/163/163/163_...
overview               Ideally located in the prime touristic area of...
rates_from                                                           NaN
continent_id                                                           2
continent_name                                                      Asia
city_id                                                            13170
country_id                                                            38
number_of_reviews                                                   1713
rating_average                                                       8.1
rates_currency                                                       USD
rates_from_exclusive                                                 NaN
accommodation_type                                                 Hotel

In [100]:
hotel = df[['hotel_id', 'hotel_name', 'addressline1', 'city', 'state','longitude','latitude','url', 'numberrooms', 'yearopened', 'yearrenovated', 'number_of_reviews', 'rating_average', 'star_rating','accommodation_type']]
hotel.head(3)

,hotel_id,hotel_name,addressline1,city,state,longitude,latitude,url,numberrooms,yearopened,yearrenovated,number_of_reviews,rating_average,star_rating,accommodation_type
0,163,Ramana Saigon Hotel,"323 Le Van Sy Street, District 3",Ho Chi Minh City,NaN,106.678101,10.787597,https://www.agoda.com/partners/partnersearch.a...,296.0,1996.0,2015.0,1713,8.1,4.0,Hotel
1,902,Lotte Hotel Saigon,"2A-4A Ton Duc Thang Street, District 1",Ho Chi Minh City,Ho Chi Minh,106.706797,10.778689,https://www.agoda.com/partners/partnersearch.a...,283.0,2001.0,2014.0,6260,9.0,5.0,Hotel
2,2019,Victoria Hoi An Beach Resort & Spa,Cua Dai Beach,Hoi An,Quang Nam,108.369757,15.895125,https://www.agoda.com/partners/partnersearch.a...,109.0,2001.0,2011.0,2330,8.9,4.5,Resort

In [101]:
hotel.shape

(29446, 15)

In [102]:
# Step 1: Split the accommodation types by ',' and expand to individual entries
hotel['accommodation_type'] = hotel['accommodation_type'].apply(lambda x: [item.lower() for item in x.split(', ')] if isinstance(x, str) else [])

# Step 2: Use MultiLabelBinarizer to handle the one-hot encoding for lists of categories
from sklearn.preprocessing import MultiLabelBinarizer

# Initialize the binarizer
mlb = MultiLabelBinarizer()

# Fit and transform the split accommodation types
one_hot_encoded = mlb.fit_transform(hotel['accommodation_type'])

# Create a DataFrame with the one-hot encoded columns
one_hot_df = pd.DataFrame(one_hot_encoded, columns=mlb.classes_)

# Concatenate with the original DataFrame (dropping the original list column for clarity)
df_final = pd.concat([hotel.drop(columns=['accommodation_type']), one_hot_df], axis=1)

C:\Users\darkn\AppData\Local\Temp\ipykernel_36536\2744061620.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel['accommodation_type'] = hotel['accommodation_type'].apply(lambda x: [item.lower() for item in x.split(', ')] if isinstance(x, str) else [])

In [103]:
one_hot_df.columns

Index(['boat/cruise', 'capsule hotel', 'chalet', 'country house',
       'entire apartment', 'entire bungalow', 'entire house', 'entire villa',
       'farm stay', 'guesthouse/bed and breakfast',
       'holiday park/caravan park', 'homestay', 'hostel', 'hotel', 'inn',
       'lodge', 'love hotel', 'motel', 'resort', 'resort villa',
       'serviced apartment', 'tent'],
      dtype='object')

In [81]:
for col in one_hot_df.columns:
    print(col)

AttributeError: 'DataFrame' object has no attribute 'col'

In [64]:
len(one_hot_df.columns)

22

In [104]:
[(col,df_final[df_final[col]==1].shape[0]) for col in one_hot_df.columns]

[('boat/cruise', 119),
 ('capsule hotel', 17),
 ('chalet', 9),
 ('country house', 9),
 ('entire apartment', 11161),
 ('entire bungalow', 445),
 ('entire house', 3479),
 ('entire villa', 2079),
 ('farm stay', 9),
 ('guesthouse/bed and breakfast', 481),
 ('holiday park/caravan park', 12),
 ('homestay', 625),
 ('hostel', 266),
 ('hotel', 8574),
 ('inn', 17),
 ('lodge', 43),
 ('love hotel', 21),
 ('motel', 72),
 ('resort', 680),
 ('resort villa', 302),
 ('serviced apartment', 1166),
 ('tent', 11)]

In [86]:
# entire apartment

In [112]:
df_final[df_final['entire apartment']==1].url.values

array(['https://www.agoda.com/partners/partnersearch.aspx?hid=165512',
       'https://www.agoda.com/partners/partnersearch.aspx?hid=281646',
       'https://www.agoda.com/partners/partnersearch.aspx?hid=283741',
       ...,
       'https://www.agoda.com/partners/partnersearch.aspx?hid=52543438',
       'https://www.agoda.com/partners/partnersearch.aspx?hid=52544248',
       'https://www.agoda.com/partners/partnersearch.aspx?hid=52544878'],
      dtype=object)

In [114]:
entire_apartment = df_final[df_final['entire apartment']==1]

In [116]:
sample = entire_apartment.sample(n = 500, random_state = 42)

In [118]:
sample.url.values[0]

'https://www.agoda.com/partners/partnersearch.aspx?hid=45581191'

In [119]:
import requests

def check_url_status(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
    }
    try:
        response = requests.get(url, headers=headers)
        if response.status_code == 404:
            return 0  # URL not accessible (404)
        else:
            return 1  # URL accessible
    except requests.exceptions.RequestException:
        return 0  # Return 0 if there is any other exception (e.g., network error)

# Example usage
url = sample.url.values[0]
status = check_url_status(url)
print(status)

1

In [9]:
driver = webdriver.Chrome(chrome_options)
driver.get(url)

In [5]:
elem = driver.find_element(By.CSS_SELECTOR, "a[data-element-name='property-card-content']")
href = elem.get_attribute('href')
href

'https://www.agoda.com/ramana-saigon-hotel/hotel/ho-chi-minh-city-vn.html?finalPriceView=1&isShowMobileAppPrice=false&cid=-1&numberOfBedrooms=&familyMode=false&adults=1&children=0&rooms=1&maxRooms=0&checkIn=2024-11-21&isCalendarCallout=false&childAges=&numberOfGuest=0&missingChildAges=false&travellerType=-1&showReviewSubmissionEntry=false&currencyCode=VND&isFreeOccSearch=false&los=1&searchrequestid=4caef570-c3cf-416e-b0b7-e9c54c3d75be'

In [120]:
df_final.to_csv('vietnam_accommodation.csv', index=False, encoding='utf-8-sig')

In [18]:
url_edited(href)

'https://www.agoda.com/vi-vn/ramana-saigon-hotel/hotel/ho-chi-minh-city-vn.html'

In [17]:
from urllib.parse import urlparse, urlunparse

# Original URL
def url_edited(url):
    try:
        parsed_url = urlparse(url)
        new_path = "/vi-vn" + parsed_url.path
        return urlunparse(parsed_url._replace(path=new_path, query=""))
    except:
        return []

In [ ]:
url_edited

In [43]:
# Ensure each entry in 'accommodation_type' is a list of labels
df['accommodation_type'] = df['accommodation_type'].apply(lambda x: [item.lower() for item in x.split(', ')] if isinstance(x, str) else [])

# Verify the conversion
print(df['accommodation_type'].head())  # This should display lists of labels for each row

0     [hotel]
1     [hotel]
2    [resort]
3     [hotel]
4     [hotel]
Name: accommodation_type, dtype: object

In [44]:
# Split the 'accommodation_type' column by commas and expand into multiple one-hot columns
# First, clean up spaces around commas, then split and apply one-hot encoding

# Step 1: Split the accommodation types by ',' and expand to individual entries
df['accommodation_type'] = df['accommodation_type'].apply(lambda x: [item.lower() for item in x.split(', ')] if isinstance(x, str) else [])

# Step 2: Use MultiLabelBinarizer to handle the one-hot encoding for lists of categories
from sklearn.preprocessing import MultiLabelBinarizer

# Initialize the binarizer
mlb = MultiLabelBinarizer()

# Fit and transform the split accommodation types
one_hot_encoded = mlb.fit_transform(df['accommodation_type'])

# Create a DataFrame with the one-hot encoded columns
one_hot_df = pd.DataFrame(one_hot_encoded, columns=mlb.classes_)

# Concatenate with the original DataFrame (dropping the original list column for clarity)
df_final = pd.concat([df.drop(columns=['accommodation_type']), one_hot_df], axis=1)

# Display the final DataFrame to the user
# tools.display_dataframe_to_user(name="Accommodation One-Hot Encoded with MultiLabelBinarizer", dataframe=df_final)

In [45]:
df_final

,hotel_id,chain_id,chain_name,brand_id,brand_name,hotel_name,hotel_formerly_name,hotel_translated_name,addressline1,addressline2,...,hostel,hotel,inn,lodge,love hotel,motel,resort,resort villa,serviced apartment,tent
0,163,0,No chain,0,NaN,Ramana Saigon Hotel,Amara Hotel,Ramana Saigon Hotel,"323 Le Van Sy Street, District 3",NaN,...,0,1,0,0,0,0,0,0,0,0
1,902,0,No chain,0,NaN,Lotte Hotel Saigon,Legend Hotel Saigon,Lotte Hotel Saigon,"2A-4A Ton Duc Thang Street, District 1",NaN,...,0,1,0,0,0,0,0,0,0,0
2,2019,0,No chain,894,No brand,Victoria Hoi An Beach Resort & Spa,NaN,Victoria Hoi An Beach Resort & Spa,Cua Dai Beach,NaN,...,0,0,0,0,0,0,1,0,0,0
3,3274,27,Pan Pacific Hotels and Resorts,1004,PARKROYAL Hotels & Resorts,PARKROYAL Saigon,Parkroyal Saigon Hotel,PARKROYAL Saigon,"309B-311 Nguyen Van Troi Street, Tan Binh Dist",NaN,...,0,1,0,0,0,0,0,0,0,0
4,9195,21,Marriott,109,Renaissance Hotels,Renaissance Riverside Hotel Saigon,Renaissance Riverside Hotel,Renaissance Riverside Hotel Saigon,8-15 Ton Duc Thang Street,NaN,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29441,52541920,0,No chain,894,No brand,Wind beach Villa,NaN,Wind beach Villa,"Phan Thiết, Tiến Thành",Wind beach villa 1.7 0341,...,0,0,0,0,0,0,0,0,0,0
29442,52541929,0,No chain,894,No brand,Moonlight FLC Sầm Sơn,NaN,Moonlight FLC Sầm Sơn,"Lk16, LK 16 Khu đô thị sinh thái FLC, phường Q...",Moonlight Hotel,...,0,1,0,0,0,0,0,0,0,0
29443,52543438,0,No chain,894,No brand,Heart of Quarter Affordable price,NaN,Heart of Quarter Affordable price,"7 P. Chợ Gạo, Hàng Buồm",2,...,0,0,0,0,0,0,0,0,0,0
29444,52544248,0,No chain,894,No brand,KHÁCH SẠN ÁNH DƯƠNG,NaN,KHÁCH SẠN ÁNH DƯƠNG,", Thành phố Qui Nhơn",NaN,...,0,0,0,0,0,0,0,0,0,0
29445,52544878,0,No chain,894,No brand,LT Housing-Vinhomes Skylake-near Keangnam Land...,NaN,LT Housing-Vinhomes Skylake-near Keangnam Land...,Vinhomes Skylake - Phạm Hùng - Nam Từ Liêm - H...,Vinhomes Skylake/City View Pham Hung,...,0,0,0,0,0,0,0,0,0,0

In [31]:
# Initialize the binarizer
mlb = MultiLabelBinarizer()

# Fit and transform the split accommodation types
one_hot_encoded = mlb.fit_transform(df['accommodation_type'])

TypeError: 'float' object is not iterable

In [34]:
one_hot_encoded

,boat/cruise,capsule hotel,country house,entire apartment,entire bungalow,entire house,entire villa,farm stay,guesthouse/bed and breakfast,holiday park/caravan park,...,hostel,hotel,inn,lodge,love hotel,motel,resort,resort villa,serviced apartment,tent
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29441,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29442,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
29443,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29444,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29445,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0